name: recipes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  introduction_screen: ^2.1.0
  renovation_core: ^1.1.0
  salomon_bottom_bar: ^3.2.0
  simple_animations: 1.3.3
  swipable_stack: ^1.2.0

dev_dependencies:
  build_runner: ^1.7.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.0.0
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg
